# Generated by Django 2.2.4 on 2019-10-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='gameResult',
        #     fields=[
        #         ('id', models.IntegerField(primary_key=True, serialize=False)),
        #         ('userId', models.CharField(max_length=30)),
        #         ('line', models.CharField(max_length=30)),
        #         ('championId', models.CharField(max_length=30)),
        #         ('win', models.IntegerField()),
        #         ('kills', models.IntegerField()),
        #         ('death', models.IntegerField()),
        #         ('assists', models.IntegerField()),
        #     ],
        # ),
        migrations.CreateModel(
            name='item_data2',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('char_id', models.IntegerField(blank=True, default=0, null=True)),
                ('item_id', models.IntegerField(default=0, null=True)),
                ('item_cnt', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
