# Generated by Django 2.2.4 on 2019-10-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_duodata_gameresult_name_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='name_data',
            old_name='item_id',
            new_name='key',
        ),
        migrations.AlterField(
            model_name='name_data',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
