# Generated by Django 2.2.4 on 2019-10-04 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pickban'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickban',
            old_name='char_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='pickban',
            old_name='char_name',
            new_name='name',
        ),
    ]
