# Generated by Django 2.2.4 on 2019-10-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191004_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='itempick',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_cnt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamData',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('team1_Win', models.CharField(max_length=30)),
                ('team1_firstBlood', models.CharField(max_length=30)),
                ('team1_firstTower', models.CharField(max_length=30)),
                ('team1_firstInhibitor', models.CharField(max_length=30)),
                ('team1_firstBaron', models.CharField(max_length=30)),
                ('team1_firstDragon', models.CharField(max_length=30)),
                ('team1_firstRiftHerald', models.CharField(max_length=30)),
                ('team1_towerKills', models.CharField(max_length=30)),
                ('team1_inhibitorKills', models.CharField(max_length=30)),
                ('team1_baronKills', models.CharField(max_length=30)),
                ('team1_dragonKills', models.CharField(max_length=30)),
                ('team1_vilemawKills', models.CharField(max_length=30)),
                ('team1_riftHeraldKills', models.CharField(max_length=30)),
                ('team1_dominionVictoryScore', models.CharField(max_length=30)),
                ('team2_Win', models.CharField(max_length=30)),
                ('team2_firstBlood', models.CharField(max_length=30)),
                ('team2_firstTower', models.CharField(max_length=30)),
                ('team2_firstInhibitor', models.CharField(max_length=30)),
                ('team2_firstBaron', models.CharField(max_length=30)),
                ('team2_firstDragon', models.CharField(max_length=30)),
                ('team2_firstRiftHerald', models.CharField(max_length=30)),
                ('team2_towerKills', models.CharField(max_length=30)),
                ('team2_inhibitorKills', models.CharField(max_length=30)),
                ('team2_baronKills', models.CharField(max_length=30)),
                ('team2_dragonKills', models.CharField(max_length=30)),
                ('team2_vilemawKills', models.CharField(max_length=30)),
                ('team2_riftHeraldKills', models.CharField(max_length=30)),
                ('team2_dominionVictoryScore', models.CharField(max_length=30)),
            ],
        ),
    ]
