# Generated by Django 2.2.4 on 2019-10-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_itempick_teamdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bancount',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('char_id', models.IntegerField(default=0, null=True)),
                ('ban_char_id', models.IntegerField(default=0, null=True)),
                ('cnt', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
