# Generated by Django 2.2.4 on 2019-10-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_bancount'),
    ]

    operations = [
        migrations.CreateModel(
            name='naivedata',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Bot1', models.CharField(max_length=10)),
                ('Bot2', models.CharField(max_length=10)),
                ('Bot3', models.CharField(max_length=10)),
                ('Bot4', models.CharField(max_length=10)),
                ('Bot5', models.CharField(max_length=10)),
                ('fBlood', models.CharField(max_length=10)),
                ('fT', models.CharField(max_length=10)),
                ('fD', models.CharField(max_length=10)),
                ('fB', models.CharField(max_length=10)),
                ('TK', models.CharField(max_length=10)),
                ('DK', models.CharField(max_length=10)),
                ('BK', models.CharField(max_length=10)),
                ('Win', models.CharField(max_length=10)),
                ('all', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Bancount',
            new_name='Bancount3',
        ),
        migrations.AddField(
            model_name='teamdata',
            name='gameduration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='team1_baronKills',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='team1_dominionVictoryScore',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='team1_dragonKills',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='team1_firstBaron',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='team1_firstBlood',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='team1_firstDragon',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='team1_firstInhibitor',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='team1_firstRiftHerald',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='team1_firstTower',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='team1_inhibitorKills',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='team1_riftHeraldKills',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='team1_towerKills',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='team1_vilemawKills',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='team2_baronKills',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='team2_dominionVictoryScore',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='team2_dragonKills',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='team2_firstBaron',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='team2_firstBlood',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='team2_firstDragon',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='team2_firstInhibitor',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='team2_firstRiftHerald',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='team2_firstTower',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='team2_inhibitorKills',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='team2_riftHeraldKills',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='team2_towerKills',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='team2_vilemawKills',
            field=models.IntegerField(),
        ),
    ]
